name: My PublicCode Workflow

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update publiccode.yaml
        uses: OpenCatalogi/publiccode-action@e116576bbdcf46f3aaf3ebc4eaaf10b832fd7757
